app/main/importation/__init__.py
#!/usr/bin/env python
# encoding: utf-8
# -------------------------------------------------------------------------------
# version:      ??
# author:       fernando
# license:      MIT License
# contact:      iw518@163.com
# purpose:      __init__.py
# date:         2017-10-05
# copyright:    copyright  2017 Xu, Aiwu
# -------------------------------------------------------------------------------
from flask import Blueprint

importation = Blueprint('importation', __name__)
from . import views

app/main/importation/views.py
#!/usr/bin/env python
# encoding: utf-8
# -------------------------------------------------------------------------------
# version:      ??
# author:       fernando
# license:      MIT License
# contact:      iw518@163.com
# purpose:      views
# date:         2017-10-05
# copyright:    copyright  2017 Xu, Aiwu
# -------------------------------------------------------------------------------

import os
from flask import request, render_template, current_app

from config import cleandir
from . import importation


@importation.route('/cpt_txt', methods=['POST', 'GET'])
def cpt_txt():
    upload_path = current_app.config.get('UPLOAD_FOLDER')
    if request.method == 'POST':
        file = request.files['file']
        file.save(os.path.join(upload_path, 'cpt', 'txt', file.filename))
    cleandir(upload_path)
    return render_template('importation/cpt_txt.html')

app/templates/importation/cpt_txt.html
{% extends "base.html" %}
{% block css %}
{% endblock %}
{% block toolbar %}
{% endblock %}
{% block main %}
    <div id="setting_div" class="col-sm-10 col-sm-offset-1">
        <div id="filelist"></div>
        <br/>
        <div id="container">
            <a id="pickfiles" href="javascript:">[选择文件]</a>
            <a id="uploadfiles" href="javascript:">[确定上传]</a>
        </div>
        <br/>
        <pre id="console"></pre>
    </div>

{% endblock %}
{% block script %}
    {{ super() }}
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plupload.min.js') }}"></script>
    <script type="text/javascript">
        // plupload
        var uploader = new plupload.Uploader({
            runtimes: 'html5',
            browse_button: 'pickfiles', // you can pass an id...
            container: document.getElementById('container'), // ... or DOM Element itself
            url: '{{url_for('importation.cpt_txt')}}',
            filters: {
                max_file_size: '1mb',
                mime_types: [
                    {title: "Access files", extensions: "txt"},
                ]
            },

            init: {
                PostInit: function () {
                    document.getElementById('filelist').innerHTML = '';

                    document.getElementById('uploadfiles').onclick = function () {
                        uploader.start();
                        //ajax上传，上传完毕后要跳转
                        window.location.href = "{{ url_for('printing.prtcptdata') }}";
                        return false;
                    };
                },

                FilesAdded: function (up, files) {
                    plupload.each(files, function (file) {
                        document.getElementById('filelist').innerHTML += '<div id="' + file.id + '">' + file.name + ' (' + plupload.formatSize(file.size) + ') <b></b></div>';
                    });
                },

                UploadProgress: function (up, file) {
                    document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
                },

                Error: function (up, err) {
                    document.getElementById('console').appendChild(document.createTextNode("\nError #" + err.code + ": " + err.message));
                }
            }
        });

        uploader.init();

    </script>
{% endblock %}