app/main/setting/__init__.py
#!/usr/bin/env python
# encoding: utf-8
# -------------------------------------------------------------------------------
# version:      ??
# author:       fernando
# license:      MIT License
# contact:      iw518@163.com
# purpose:      __init__
# date:         2016-07-27
# copyright:    copyright  2016 Xu, Aiwu
# -------------------------------------------------------------------------------
from flask import Blueprint

setting = Blueprint('setting', __name__)
from . import views

app/main/setting/views.py
#!/usr/bin/env python
# encoding: utf-8
# -------------------------------------------------------------------------------
# version:      ??
# author:       fernando
# license:      MIT License
# contact:      iw518@163.com
# purpose:      views
# date:         2017-08-05
# copyright:    copyright  2017 Xu, Aiwu
# -------------------------------------------------------------------------------
import os
from flask import request, render_template, jsonify, session

from app.services.core import import_xml
from app.services.dataset import MSSQL
from config import ROOTDIR
from . import setting


@setting.route("/layer_template", methods=['POST', 'GET'])
def layer_template():
    layerConfigDict = import_xml()
    if request.method == 'POST':
        return jsonify(result=layerConfigDict)
    else:
        return render_template(
            "setting/layer_template.html",
            layerConfigDict=layerConfigDict
        )


# 不同POST在一个函数中的写法，如果分开在两个函数中，要更简单
@setting.route('/data_source', methods=['POST', 'GET'])
def data_source():
    if request.method == 'POST':
        print(request.form)
        if "name" in request.form:
            file = request.files['file']
            if file:
                file.save(os.path.join(ROOTDIR, 'upload', 'database', "Tran_shgeodb.mdb"))
        if "edition" in request.form:
            edition = request.form["edition"]
            session['edition'] = edition
    return render_template('setting/data_source.html', edition=MSSQL.edition)

app/templates/setting/data_source.html
{% extends "base.html" %}
{% block css %}
{% endblock %}
{% block toolbar %}
{% endblock %}
{% block main %}

    <div class="radio-group">
        <div class="radio">
            <label>
                <input type="radio" name="optionsRadios" id="optionsRadios2" value="Enterprise">
                网络版
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="Personal">
                单机版
            </label>
        </div>
    </div>
    <div id="setting_div" class="col-sm-10 col-sm-offset-1" style="display: none">
        <div id="filelist"></div>
        <br/>
        <div id="container">
            <a id="pickfiles" href="javascript:">[选择文件]</a>
            <a id="uploadfiles" href="javascript:">[确定上传]</a>
        </div>
        <br/>
        <pre id="console"></pre>
    </div>

{% endblock %}
{% block script %}
    {{ super() }}
    <script type="text/javascript">
        //打开或关闭单机版上传数据库接口

        $(function () {
            var $option = $("div.radio-group:first").find("input:radio[name='optionsRadios']");
            //获得当前运行模式
            $option.each(function () {
                if ($(this).val() == '{{ edition }}') {
                    $(this).attr('checked', true);
                }
                else {
                    $(this).attr('checked', false);
                }
            });

            $option.on("click", function () {
                var edition = $(this).attr('checked', 'true').val();
                var myurl = "{{url_for('setting.data_source')}}";
                var mydata = {"edition": edition};
                $.ajax({
                    url: myurl,
                    data: mydata,
                    type: "POST",
                    dataType: "json",
                    success: function () {
                    }
                });
                if (edition == "Personal") {
                    if ($("#setting_div").is(":visible") == false) {
                        $("#setting_div").show();
                    }
                }
                else {
                    if ($("#setting_div").is(":visible")) {
                        $("#setting_div").hide();
                    }
                }


            });
        });</script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plupload.min.js') }}"></script>
    <script type="text/javascript">
        // plupload
        var uploader = new plupload.Uploader({
            runtimes: 'html5',
            browse_button: 'pickfiles', // you can pass an id...
            container: document.getElementById('container'), // ... or DOM Element itself
            url: '{{url_for('setting.data_source')}}',
            filters: {
                max_file_size: '10mb',
                mime_types: [
                    {title: "Access files", extensions: "mdb"},
                ]
            },

            init: {
                PostInit: function () {
                    document.getElementById('filelist').innerHTML = '';

                    document.getElementById('uploadfiles').onclick = function () {
                        uploader.start();
                        window.location.href = "{{ url_for('main.index') }}";
                        return false;
                    };
                },

                FilesAdded: function (up, files) {
                    plupload.each(files, function (file) {
                        document.getElementById('filelist').innerHTML += '<div id="' + file.id + '">' + file.name + ' (' + plupload.formatSize(file.size) + ') <b></b></div>';
                    });
                },

                UploadProgress: function (up, file) {
                    document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
                },

                Error: function (up, err) {
                    document.getElementById('console').appendChild(document.createTextNode("\nError #" + err.code + ": " + err.message));
                }
            }
        });

        uploader.init();

    </script>
{% endblock %}

app/templates/setting/layer_template.html
{% extends "project_home.html" %}

{% block css %}
    {{super()}}
    <style type="text/css">
    #tbl_layerInf{
        background-color: #cccccc;
        border:2px solid black;
        padding: 5px 5px;
    }

    #tbl_layerInf th,td{
        border:1px solid black;
        font-size: 14px;
        text-align: center;
        white-space:nowrap;
    }

    #tbl_layerInf input{
        border-width: 0px;
        width:100%;
        height: 100%;
        text-align: center;
    }
    </style>
{% endblock %}

{% block main %}
    <div id="printArea">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <h4 style="text-align: center;"><strong>土层模版</strong></h4>
                <hr/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <table id="tbl_layerInf">
                    <thead>
                        <tr>
                            <td>序号</td>
                            {% for key,value in layerConfigDict.items()%}
                            <td>{{key}}</td>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in range(0 ,60) %}
                        <tr>
                            <td>{{loop.index}}</td>
                            {% for key,value in layerConfigDict.items()%}
                                {% if i < value|length %}
                                <td><input value={{value[i]}}></td>
                                {% else %}
                                <td><input></td>
                                {% endif %}
                            {% endfor %}                        
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>    
        </div>
    </div>
{% endblock %}

{% block script%}
    {{super()}}
{% endblock %}